### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ifndefdeadmau5** [ifndefdeadmau5/graphql-shop#2]
- [ ] Theme switching(enable dark mode & multiple color theme)
- [ ] Apply new component design
- [ ] Polish product add dialog
- [ ] Change loading component(to fancy one ideally)
